PeopleManager.Ui.Mvc/Models/ErrorViewModel.cs
namespace PeopleManager.Ui.Mvc.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PeopleManager.Ui.Mvc/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using PeopleManager.Services;
using PeopleManager.Ui.Mvc.Models;
using System.Diagnostics;

namespace PeopleManager.Ui.Mvc.Controllers
{
    public class HomeController : Controller
    {
        private readonly PersonService _personService;

        public HomeController(PersonService personService)
        {
            _personService = personService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var people = _personService.Find();
            return View(people);
        }

        [HttpGet]
        public IActionResult Privacy()
        {
            return View();
        }

        [HttpGet]
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [HttpGet]
        public IActionResult Detail(int id)
        {
            var person = _personService.Get(id);

            if (person is null)
            {
                return RedirectToAction("Index");
            }

            return View("PersonDetail", person);
        }
    }
}

PeopleManager.Ui.Mvc/Controllers/PeopleController.cs
using Microsoft.AspNetCore.Mvc;
using PeopleManager.Model;
using PeopleManager.Services;

namespace PeopleManager.Ui.Mvc.Controllers
{
    public class PeopleController : Controller
    {
        private readonly PersonService _personService;

        public PeopleController(PersonService personService)
        {
            _personService = personService;
        }


        [HttpGet]
        public IActionResult Index()
        {
            var people = _personService.Find();
            return View(people);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Person person)
        {
            if (!ModelState.IsValid)
            {
                return View(person);
            }

            _personService.Create(person);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var person = _personService.Get(id);

            if (person is null)
            {
                return RedirectToAction("Index");
            }

            return View(person);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit([FromRoute]int id, [FromForm]Person person)
        {
            if (!ModelState.IsValid)
            {
                return View(person);
            }

            _personService.Update(id, person);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var person = _personService.Get(id);

            if (person is null)
            {
                return RedirectToAction("Index");
            }

            return View(person);
        }

        [HttpPost("People/Delete/{id:int?}")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            _personService.Delete(id);

            return RedirectToAction("Index");
        }
    }
}

PeopleManager.Ui.Mvc/Controllers/VehiclesController.cs
using JetBrains.Annotations;
using Microsoft.AspNetCore.Mvc;
using PeopleManager.Model;
using PeopleManager.Services;

namespace PeopleManager.Ui.Mvc.Controllers
{
    public class VehiclesController : Controller
    {
        private readonly VehicleService _vehicleService;
        private readonly PersonService _personService;

        public VehiclesController(VehicleService vehicleService, PersonService personService)
        {
            _vehicleService = vehicleService;
            _personService = personService;
        }


        [HttpGet]
        public IActionResult Index()
        {
            var vehicles = _vehicleService.Find();

            return View(vehicles);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return CreateEditView("Create");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Vehicle vehicle)
        {
            if (!ModelState.IsValid)
            {
                return CreateEditView("Create", vehicle);
            }

            _vehicleService.Create(vehicle);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var vehicle = _vehicleService.Get(id);

            if (vehicle is null)
            {
                return RedirectToAction("Index");
            }

            return CreateEditView("Edit", vehicle);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit([FromRoute]int id, [FromForm]Vehicle vehicle)
        {
            if (!ModelState.IsValid)
            {
                return CreateEditView("Edit", vehicle);
            }

            _vehicleService.Update(id, vehicle);

            return RedirectToAction("Index");
        }
        
        private IActionResult CreateEditView([AspMvcView]string viewName, Vehicle? vehicle = null)
        {
            var people = _personService.Find();

            ViewBag.People = people;

            return View(viewName, vehicle);
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var vehicle = _vehicleService.Get(id);

            if (vehicle is null)
            {
                return RedirectToAction("Index");
            }

            return View(vehicle);
        }

        [HttpPost("Vehicles/Delete/{id:int?}")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            _vehicleService.Delete(id);

            return RedirectToAction("Index");
        }
    }
}

PeopleManager.Ui.Mvc/Views/Home/Index.cshtml
@model IList<Person>

@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome Bavo</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

<div class="row">
    @foreach (var person in Model)
    {
        <div class="col-4">
            <partial name="PersonCardPartial" model="person"/>
        </div>
    }
</div>

PeopleManager.Ui.Mvc/Views/Home/PersonCardPartial.cshtml
@model Person

<div class="card">
    <div class="card-header">
        <a asp-action="Detail" asp-route-id="@Model.Id">
            <h2>@Model.FirstName @Model.LastName</h2>
        </a>
    </div>
    <div class="card-body">
        <a class="btn btn-outline-primary" href="mailto:@Model.Email">Contact</a>
    </div>
</div>

PeopleManager.Ui.Mvc/Views/Home/PersonDetail.cshtml
@model Person

<div class="row">
    <div class="col-4"><strong>First name:</strong></div>
    <div class="col-8">@Model.FirstName</div>
</div>
<div class="row">
    <div class="col-4"><strong>Last name:</strong></div>
    <div class="col-8">@Model.LastName</div>
</div>
<div class="row">
    <div class="col-4"><strong>Email:</strong></div>
    <div class="col-8">@Model.Email</div>
</div>
<div class="row">
    <div class="col-4"><strong>Description:</strong></div>
    <div class="col-8">@Model.Description</div>
</div>

PeopleManager.Ui.Mvc/Views/People/Create.cshtml
@model Person

@{
    ViewBag.Title = "Create Person";
}

<h1>@ViewBag.Title</h1>

<form method="post">
    <partial name="CreateEditPartial" model="Model"/>

    <button type="submit" class="btn btn-primary">Create</button>
</form>

@section Scripts
{
    <partial name="_ValidationScriptsPartial" />
}

PeopleManager.Ui.Mvc/Views/People/CreateEditPartial.cshtml
@model Person

<div asp-validation-summary="ModelOnly"></div>

<div class="mb-3">
    <label asp-for="FirstName" class="form-label"></label>
    <input asp-for="FirstName" class="form-control" />
    <span asp-validation-for="FirstName"></span>
</div>
<div class="mb-3">
    <label asp-for="LastName" class="form-label">Last Name</label>
    <input asp-for="LastName" class="form-control" />
    <span asp-validation-for="LastName"></span>
</div>
<div class="mb-3">
    <label asp-for="Email" class="form-label"></label>
    <input asp-for="Email" class="form-control" />
    <span asp-validation-for="Email"></span>
</div>
<div class="mb-3">
    <label asp-for="Description" class="form-label"></label>
    <textarea asp-for="Description" class="form-control"></textarea>
    <span asp-validation-for="Description"></span>
</div>

PeopleManager.Ui.Mvc/Views/People/Delete.cshtml
@model Person

@{
    ViewBag.Title = "Delete Person";
}

<h1>@ViewBag.Title</h1>

<form method="post">
    <p>Are you sure you want to delete @Model.FirstName @Model.LastName (@Model.Email)?</p>
    <a asp-action="Index" class="btn btn-light">&lt; No</a>
    <button type="submit" class="btn btn-danger">Yes</button>
</form>

PeopleManager.Ui.Mvc/Views/People/Edit.cshtml
@model Person

@{
    ViewBag.Title = "Edit Person";
}

<h1>@ViewBag.Title</h1>

<form method="post">
    <partial name="CreateEditPartial" model="Model" />

    <button type="submit" class="btn btn-primary">Save</button>
</form>

@section Scripts
{
    <partial name="_ValidationScriptsPartial" />
}

PeopleManager.Ui.Mvc/Views/People/Index.cshtml
@model IList<Person>

@{
    ViewData["Title"] = "People Index";
}

<h1>People Index</h1>

<a asp-action="Create" class="btn btn-primary">Create new Person</a>

<table class="table table-striped">
    <thead>
    <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Email</th>
        <th>Actions</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var person in Model)
    {
        <partial name="PersonRowPartial" model="person"/>
    }
    </tbody>
</table>

@section Modals
{
    <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteModalLabel">Delete Person</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <p>Are you sure you want to delete this person?</p>
                </div>
                <div class="modal-footer">
                    <form method="post" asp-action="DeleteConfirmed">
                        <input type="hidden" name="id"/>
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No</button>
                        <button type="submit" class="btn btn-primary">Yes</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
}

@section Scripts
{
    <script>
        $(function(){
            $("button[data-role='delete']").on("click", 
                function()
                {
                    let id = $(this).data("id");
                    $("input[name='id']").val(id);
                });
        });
    </script>
}

PeopleManager.Ui.Mvc/Views/People/PersonRowPartial.cshtml
@model Person

<tr>
    <td>@Model.FirstName</td>
    <td>@Model.LastName</td>
    <td>
        <a href="mailto:@Model.Email">
            @Model.Email
        </a>
    </td>
    <td>
        <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-success">Edit</a>
        <a asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-danger">Delete</a>
        <button type="button" 
                class="btn btn-danger" 
                data-bs-toggle="modal" 
                data-bs-target="#deleteModal"
                data-id="@Model.Id"
                data-role="delete">
            Delete with modal
        </button>
    </td>
</tr>

PeopleManager.Ui.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PeopleManager.Ui.Mvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PeopleManager.Ui.Mvc.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PeopleManager.Ui.Mvc</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="People" asp-action="Index">People</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Vehicles" asp-action="Index">Vehicles</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - PeopleManager.Ui.Mvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    @await RenderSectionAsync("Modals", required: false)

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

PeopleManager.Ui.Mvc/Views/Vehicles/Create.cshtml
@model Vehicle

@{
    ViewBag.Title = "Create Vehicle";
}

<h1>@ViewBag.Title</h1>

<form method="post">
    <partial name="CreateEditPartial" model="Model"/>

    <button type="submit" class="btn btn-primary">Create</button>
</form>

@section Scripts
{
    <partial name="_ValidationScriptsPartial" />
}

PeopleManager.Ui.Mvc/Views/Vehicles/CreateEditPartial.cshtml
@model Vehicle

@{
    var people = (IList<Person>)ViewBag.People;
}

<div asp-validation-summary="ModelOnly"></div>

<div class="mb-3">
    <label asp-for="LicensePlate" class="form-label"></label>
    <input asp-for="LicensePlate" class="form-control" />
    <span asp-validation-for="LicensePlate"></span>
</div>
<div class="mb-3">
    <label asp-for="Brand" class="form-label"></label>
    <input asp-for="Brand" class="form-control" />
    <span asp-validation-for="Brand"></span>
</div>
<div class="mb-3">
    <label asp-for="Type" class="form-label"></label>
    <input asp-for="Type" class="form-control" />
    <span asp-validation-for="Type"></span>
</div>
<div class="mb-3">
    <label asp-for="ResponsiblePersonId" class="form-label">Choose a responsible person:</label>
    <select asp-for="ResponsiblePersonId" class="form-control">
        <option value="">No responsible person</option>
        @foreach (var person in people)
        {
            <option value="@person.Id">@person.FirstName @person.LastName</option>
        }
    </select>
</div>

PeopleManager.Ui.Mvc/Views/Vehicles/Delete.cshtml
@model Vehicle

@{
    ViewBag.Title = "Delete Vehicle";
}

<h1>@ViewBag.Title</h1>

<form method="post">
    <p>
        Are you sure you want to delete @Model.LicensePlate?
    </p>
    <a asp-action="Index" class="btn btn-light">&lt; No</a>
    <button type="submit" class="btn btn-danger">Yes</button>
</form>

PeopleManager.Ui.Mvc/Views/Vehicles/Edit.cshtml
@model Vehicle

@{
    ViewBag.Title = "Edit Vehicle";
}

<h1>@ViewBag.Title</h1>

<form method="post">
    <partial name="CreateEditPartial" model="Model" />

    <button type="submit" class="btn btn-primary">Save</button>
</form>

@section Scripts
{
    <partial name="_ValidationScriptsPartial" />
}

PeopleManager.Ui.Mvc/Views/Vehicles/Index.cshtml
@model IList<Vehicle>

@{
    ViewData["Title"] = "Vehicle Index";
}

<h1>Vehicle Index</h1>

<a asp-action="Create" class="btn btn-primary">Create new Vehicle</a>

<table class="table table-striped">
    <thead>
    <tr>
        <th>License plate</th>
        <th>Brand</th>
        <th>Type</th>
        <th>Responsible Person</th>
        <th>Actions</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var vehicle in Model)
    {
        <partial name="VehicleRowPartial" model="vehicle"/>
    }
    </tbody>
</table>

@section Modals
{
    <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteModalLabel">Delete Vehicle</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <p>Are you sure you want to delete this vehicle?</p>
                </div>
                <div class="modal-footer">
                    <form method="post" asp-action="DeleteConfirmed">
                        <input type="hidden" name="id"/>
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No</button>
                        <button type="submit" class="btn btn-primary">Yes</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
}

@section Scripts
{
    <script>
        $(function(){
            $("button[data-role='delete']").on("click", 
                function()
                {
                    let id = $(this).data("id");
                    $("input[name='id']").val(id);
                });
        });
    </script>
}

PeopleManager.Ui.Mvc/Views/Vehicles/VehicleRowPartial.cshtml
@model Vehicle

<tr>
    <td>@Model.LicensePlate</td>
    <td>@Model.Brand</td>
    <td>@Model.Type</td>
    <td>
        @if (Model.ResponsiblePerson is not null)
        {
            @: @Model.ResponsiblePerson.FirstName @Model.ResponsiblePerson.LastName
        }
    </td>
    <td>
        <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-success">Edit</a>
        <a asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-danger">Delete</a>
        <button type="button" 
                class="btn btn-danger" 
                data-bs-toggle="modal" 
                data-bs-target="#deleteModal"
                data-id="@Model.Id"
                data-role="delete">
            Delete with modal
        </button>
    </td>
</tr>